SELECT

/**
Creación:
https://vinasantarita.softexpert.com/
2022-04-18. Andrés Del Río. Consultas estándar de análsis de riesgo y análisis de control combinadas.
Versión: 2.1.7.112
Panel de análisis: REPRIECON-Reporte Riesgos y Controles
Modificaciones:
<AAAA-MM-DD>. Autor. Descripción
<AAAA-MM-DD>. Autor. Descripción
**/

CONTROLES.IDCONTROLANALYSIS ID_ANALISIS_CONTROL,
CONTROLES.NMCONTROL NOMBRE_CONTROL,
CONTROLES.TYPE TIPO_CONTROL,
CONTROLES.DSCONTROLANALYSIS NOTA_CONTROL,
CONTROLES.DSCONTROL DESCRIPCION_CONTROL,
CONTROLES.NMEVALRESULT_REAL RESULTADO_CONTROL,
CONTROLES.VLEVALRESULTREAL PUNTUACION_CONTROL,
CONTROLES.NMRELEVANT CONTROL_CLAVE,
CONTROLES.NMIMPLEMENT IMPLEMENTACION_CONTROL,
CONTROLES.NMAUTOMATIONTYPE TIPO_AUTOMATIZACION,
CONTROLES.NMCONTROLCHARACT CARACT_CONTROL,
CONTROLES.NMCONTROLFREQ FRECUENCIA_CONTROL,
CONTROLES.NMUSER RESPONSABLE_CONTROL,
CONTROLES.NMTEAM GRUPO_RESP_CONTROL,
CONTROLES.DTCONTROLANAEVAL FECHA_EVAL_CONTROL,

RIESGOS.*
FROM
(SELECT
        RISKANA.CDASSOCRISKANA,
        RISKANA.CDASSOCRISKANA AS CDASSOCANA,
        RISKANA.CDASSOC,
        RISKANA.CDRISKANABASELINK,
        RISKANA.FGRISKANAPARENT,
        RISKANA.FGRISKASSOCTYPE,
        RIRISKANA.CDRISKANALYSIS,
        RIRISKANA.IDRISKANALYSIS || ' - ' || RIR.NMRISK AS RISK,
        RIRISKANA.CDRISKRESP,
        RIRISKANA.CDRISKTEAM,
        RIRISKANA.CDASSOC AS CDASSOCANALYSIS,
        RIRISKANA.DTNEXTEVAL,
        RIRISKANA.VLTOTAL,
        RIRISKANA.CDEVAL,
        RIRISKANA.VLEXPECTED,
        RIRISKANA.IDRISKANALYSIS,
        RIRISKANA.DSRISKANALYSIS,
        RIRISKANA.CDTOOLSANALISYS,
        RIRISKANA.CDMEASUNITY,
        RIRISKANA.VLLOSSTOTAL,
        RIRISKANA.VLRECOVERED,
        RIRISKANA.VLEVENTLOSSTOTAL,
        RIRISKANA.VLAPPETITE,
        RIRISKANA.FGSUBRISK,
        RIRISKANA.VLTOLERANCE,
        RIR.CDASSOC AS CDASSOCRISK,
        RIR.FGENABLED,
        RIR.FGVALUE,
        RIR.CDRISK,
        RIR.IDRISK AS ID,
        RIR.NMRISK,
        RIR.CDRISKTYPE,
        RIR.FGSYMBOL,
        RIR.DSRISK,
        RP.CDPLAN,
        RP.CDREVISION,
        RP.IDPLAN,
        RP.NMPLAN,
        RP.IDPLAN || ' - ' || RP.NMPLAN AS PLANN,
        RP.CDBUSINESSUNIT,
        RP.CDISOSYSTEM,
        RP.CDASSOC AS CDASSOCPLAN,
        RP.FGDEFAULT,
        RP.FGTEMPLATE,
        RP.CDRISKRESIDEVAL,
        RP.CDTEMPLATEREV,
        GNGT.CDGENTYPE,
        GNGT.NMGENTYPE AS NMTYPE,
        GNGT.IDGENTYPE || ' - ' || GNGT.NMGENTYPE AS TYPE,
        GNR.FGSTATUS AS FGREVISION,
        GNR.IDREVISION,
        GGTP.CDISOSYSTEM AS CDPROD,
        ADM.IDMEASUNITY,
        (CASE 
            WHEN RIRISKANA.CDMEASUNITY IS NOT NULL THEN ADM.IDMEASUNITY || ' - ' || ADM.NMMEASUNITY 
            ELSE NULL 
        END) AS MEASUNITY,
        ADC.IDDEPARTMENT || ' - ' || ADC.NMDEPARTMENT AS NMBUSINESSUNIT,
        ADU.IDUSER,
        ADU.NMUSER,
        ADT.IDTEAM,
        ADT.NMTEAM,
        RIRISKANAE.CDRISKANAEVAL,
        RIRISKANAE.CDASSOC AS CDASSOCRISKANAEVAL,
        RIRISKANAE.IDPERIOD,
        RIRISKANAE.DTEVAL,
        RIRISKANAE.FGCURRENT,
        RIRISKANAE.CDEVALRESULTREAL,
        RIRISKANAE.CDEVALRESULTPOT,
        RIRISKANAE.CDEVALRESULTRESID,
        RISCALC.CDEVALCTRLREAL AS CDEVALRESULTCTRLREAL,
        (CASE 
            WHEN RIRISKANAE.FGSIGNIFICANT IS NULL THEN 2 
            ELSE RIRISKANAE.FGSIGNIFICANT 
        END) AS FGSIGNIFICANT,
        GNE.IDEVAL || ' - ' || GNE.NMEVAL AS NMEVAL,
        GNE.FGTYPE AS FGEVALTYPE,
        GERU_IN.VLEVALRESULT AS VLEVALRESULTREAL,
        GER_IN.NMEVALRESULT AS NMEVALRESULT_REAL,
        GER_IN.IDCOLOR AS IDCOLOR_REAL,
        GERU_POT.VLEVALRESULT AS VLEVALRESULTPOT,
        GER_POT.NMEVALRESULT AS NMEVALRESULT_POT,
        GER_POT.IDCOLOR AS IDCOLOR_POT,
        GERU_RES.VLEVALRESULT AS VLEVALRESULTRESID,
        GER_RESID.NMEVALRESULT AS NMEVALRESULT_RESID,
        GER_RESID.IDCOLOR AS IDCOLOR_RESID,
        GER_CTRLREAL.IDCOLOR AS IDCOLOR_CTRLREAL,
        GER_CTRLREAL.NMEVALRESULT AS NMEVALRESULT_CTRLREAL,
        GERU_CTRLREAL.VLEVALRESULT AS VLEVALRESULTCTRLREAL,
        ('{"fground":"1","qtdecimal":"1"}') AS FGROUND_QTDECIMAL_JSON,
        (SELECT
            MIN(NRORDER) 
        FROM
            RIPLANITEMORDER 
        WHERE
            CDPLAN=RISKANA.CDPLAN 
            AND CDREVISION=RISKANA.CDREVISION 
            AND CDRISKANALYSIS=RISKANA.CDASSOCRISKANA) AS NRORDER,
        (CASE 
            WHEN (SELECT
                CDASSOC 
            FROM
                GNASSOCRIPLAN 
            WHERE
                CDPLAN=RP.CDPLAN 
                AND CDREVISION=RP.CDREVISION) IS NOT NULL THEN (SELECT
                CDASSOC 
            FROM
                GNASSOCRIPLAN 
            WHERE
                CDPLAN=RP.CDPLAN 
                AND CDREVISION=RP.CDREVISION) 
            ELSE (SELECT
                CDASSOC 
            FROM
                RIPLAN 
            WHERE
                CDPLAN=RP.CDPLAN 
                AND CDREVISION=RP.CDREVISION) 
        END) AS CDASSOC_PLAN,
        (CASE 
            WHEN GER_IN.FGREQCONTROL=1 THEN 1 
            WHEN GER_POT.FGREQCONTROL=1 THEN 1 
            WHEN GER_RESID.FGREQCONTROL=1 THEN 1 
            ELSE 2 
        END) AS REQCONTROL,
        (CASE 
            WHEN GER_IN.FGREQTREATMENT=1 THEN 1 
            WHEN GER_POT.FGREQTREATMENT=1 THEN 1 
            WHEN GER_RESID.FGREQTREATMENT=1 THEN 1 
            ELSE 2 
        END) AS REQTREAT,
        (SELECT
            MIN(RIRISKANADECTREE.FGRESULT) 
        FROM
            RIRISKANADECTREE 
        WHERE
            RIRISKANADECTREE.CDRISKANALYSIS=RIRISKANA.CDRISKANALYSIS) AS FGCCPRESULT,
        (( SELECT
            COUNT(1) 
        FROM
            GNSTRUCT GNS 
        INNER JOIN
            RISTRUCTCAUSE RSC 
                ON RSC.CDSTRUCT=GNS.CDSTRUCT 
        INNER JOIN
            OBCAUSE OBC 
                ON OBC.CDCAUSE=RSC.CDCAUSE 
        WHERE
            GNS.CDTOOLANALYSIS=RIRISKANA.CDTOOLSANALISYS) + (SELECT
            COUNT(1) 
        FROM
            GNSTRUCT GNS 
        INNER JOIN
            GNANALISYS GNA 
                ON GNA.CDANALISYS=GNS.CDANALISYS 
        INNER JOIN
            GNANALISYS GNANEXT 
                ON GNANEXT.CDANALISYSEXT=GNA.CDANALISYS 
        WHERE
            GNANEXT.CDTOOLSANALISYS=RIRISKANA.CDTOOLSANALISYS)) AS ASSOC_CAUSE,
        (SELECT
            COUNT(1) 
        FROM
            GNASSOCCONTROLANA GNACA 
        WHERE
            GNACA.CDASSOC=RIRISKANA.CDASSOC) AS ASSOC_CONTROL,
        (SELECT
            COUNT(1) 
        FROM
            GNASSOCRISKANA GNARA 
        WHERE
            GNARA.CDASSOC=RIRISKANA.CDASSOC) AS ASSOC_SUBRISK,
        (SELECT
            COUNT(1) 
        FROM
            RIRISKANATREATMENT 
        WHERE
            CDRISKANALYSIS=RIRISKANA.CDRISKANALYSIS 
            AND CDRISKANAEVAL IS NULL) AS ASSOC_TREATMENT,
        (SELECT
            COUNT(1) 
        FROM
            RIRISKANATREATMENT 
        WHERE
            CDRISKANALYSIS=RIRISKANA.CDRISKANALYSIS 
            AND CDRISKANAEVAL IS NULL 
            AND RIRISKANATREATMENT.CDEVALRESULT IS NOT NULL) AS RISK_RESPONSE,
        (SELECT
            COUNT(1) 
        FROM
            RIRISKANATREATMENT 
        WHERE
            CDRISKANALYSIS=RIRISKANA.CDRISKANALYSIS 
            AND CDRISKANAEVAL IS NULL 
            AND RIRISKANATREATMENT.CDACTIONPLAN IS NOT NULL) AS ACTIONPLAN_TREATMENT,
        (SELECT
            COUNT(1) 
        FROM
            RIRISKANACONSEQUE 
        WHERE
            CDRISKANALYSIS=RIRISKANA.CDRISKANALYSIS) AS ASSOC_CONSEQUENCE,
        (SELECT
            COUNT(1) 
        FROM
            RIRISKANABESTPRACT 
        WHERE
            CDRISKANALYSIS=RIRISKANA.CDRISKANALYSIS) AS ASSOC_BESTPRACTICE,
        (SELECT
            COUNT(1) 
        FROM
            RIRISKANAOBJECTIVE 
        WHERE
            CDRISKANALYSIS=RIRISKANA.CDRISKANALYSIS) AS ASSOC_OBJECTIVE,
        (SELECT
            COUNT(1) 
        FROM
            RIRISKANASOURCE 
        WHERE
            CDRISKANALYSIS=RIRISKANA.CDRISKANALYSIS) AS ASSOC_SOURCE,
        (SELECT
            COUNT(1) 
        FROM
            GNASSOCWORKFLOW GNAW 
        INNER JOIN
            WFPROCESS WFP 
                ON GNAW.IDPROCESS=WFP.IDOBJECT 
        WHERE
            WFP.FGSTATUS <= 5 
            AND WFP.CDPRODAUTOMATION=160 
            AND GNAW.CDASSOC=RIRISKANA.CDASSOC) AS ASSOC_INCIDENT,
        (SELECT
            COUNT(1) 
        FROM
            GNASSOCWORKFLOW GNAW 
        INNER JOIN
            WFPROCESS WFP 
                ON GNAW.IDPROCESS=WFP.IDOBJECT 
        WHERE
            WFP.FGSTATUS <= 5 
            AND WFP.CDPRODAUTOMATION=202 
            AND GNAW.CDASSOC=RIRISKANA.CDASSOC) AS ASSOC_PROBLEM,
        (SELECT
            COUNT(1) 
        FROM
            GNASSOCWORKFLOW GNAW 
        INNER JOIN
            WFPROCESS WFP 
                ON GNAW.IDPROCESS=WFP.IDOBJECT 
        WHERE
            WFP.FGSTATUS <= 5 
            AND GNAW.CDASSOC=RIRISKANA.CDASSOC 
            AND WFP.CDPRODAUTOMATION NOT IN (
                160, 202
            )) AS ASSOC_WORKFLOW,
        (SELECT
            COUNT(1) 
        FROM
            GNASSOCPROJECT 
        WHERE
            CDASSOC=RIRISKANA.CDASSOC) AS ASSOC_PROJECT,
        (SELECT
            COUNT(1) 
        FROM
            GNASSOCMETRIC 
        WHERE
            CDASSOC=RIRISKANA.CDASSOC) AS ASSOC_METRIC,
        (SELECT
            COUNT(1) 
        FROM
            GNASSOCACTIONPLAN 
        WHERE
            CDASSOC=RIRISKANAE.CDASSOC) AS ASSOC_ACTIONPLAN_EVAL,
        (SELECT
            COUNT(1) 
        FROM
            GNASSOCACTIONPLAN 
        WHERE
            CDASSOC=RIRISKANA.CDASSOC) AS ASSOC_ACTIONPLAN,
        (SELECT
            COUNT(1) 
        FROM
            GNASSOCDOCUMENT 
        WHERE
            CDASSOC=RIRISKANA.CDASSOC) AS ASSOC_DOCUMENT,
        (SELECT
            COUNT(1) 
        FROM
            GNASSOCATTACH 
        WHERE
            CDASSOC=RIRISKANA.CDASSOC) AS ASSOC_ATTACHMENT,
        (SELECT
            COUNT(1) 
        FROM
            GNASSOCSCSTRUCT 
        WHERE
            CDASSOC=RIRISKANA.CDASSOC) AS ASSOC_STITEM,
        (SELECT
            COUNT(1) 
        FROM
            RIRISKANACOMMENT 
        WHERE
            CDRISKANALYSIS=RIRISKANA.CDRISKANALYSIS) AS ASSOC_COMMENT,
        (CASE 
            WHEN RIR.FGVALUE=1 THEN '#{203460}' 
            ELSE '#{200629}' 
        END) AS NMRISKCLASSIFIC,
        (CASE 
            WHEN RIRISKANAE.FGSIGNIFICANT=1 THEN '#{100092}' 
            ELSE '#{100093}' 
        END) AS NMSIGNIFICANT,
        PMAPROC.IDACTIVITY AS IDPROCESS,
        PMAPROC.NMACTIVITY AS NMPROCESS,
        RIRISKANA.CDRISKANABASE,
        (CASE 
            WHEN RISKANA.FGRISKANAPARENT=1 THEN (SELECT
                IDPLAN || ' - ' || NMPLAN 
            FROM
                RIPLAN 
            WHERE
                CDASSOC=RISKANA.CDASSOC) 
            WHEN RISKANA.FGRISKANAPARENT=2 THEN (SELECT
                IDITEM || ' - ' || NMITEM 
            FROM
                RIPLANITEM RPI 
            INNER JOIN
                RIITEM RR 
                    ON RR.CDITEM=RPI.CDITEM 
            WHERE
                RPI.CDASSOC=RISKANA.CDASSOC) 
            WHEN RISKANA.FGRISKANAPARENT IN (3,
            4) THEN (SELECT
                RRA.IDRISKANALYSIS || ' - ' || RR.NMRISK 
            FROM
                RIRISKANALYSIS RRA 
            INNER JOIN
                RIRISK RR 
                    ON RR.CDRISK=RRA.CDRISK 
            WHERE
                RRA.CDASSOC=RISKANA.CDASSOC 
                AND RRA.CDRISKANALYSIS <> RISKANA.CDRISKANALYSIS) 
            WHEN RISKANA.FGRISKANAPARENT IN (5,
            6) THEN (SELECT
                IDSCMETRIC || ' - ' || NMMETRIC 
            FROM
                STSCMETRIC 
            INNER JOIN
                STMETRIC 
                    ON STMETRIC.CDMETRIC=STSCMETRIC.CDMETRIC 
            WHERE
                STSCMETRIC.CDASSOC=RISKANA.CDASSOC) 
            WHEN RISKANA.FGRISKANAPARENT=7 THEN (SELECT
                IDSCSTRUCTITEM || ' - ' || NMSCOREITEM 
            FROM
                STSCSTRUCTITEM SST 
            INNER JOIN
                STSCOREITEM SCI 
                    ON SCI.CDSCOREITEM=SST.CDSCOREITEM 
            WHERE
                SST.CDASSOC=RISKANA.CDASSOC) 
            WHEN RISKANA.FGRISKANAPARENT=8 THEN (SELECT
                COALESCE(PMAR.IDACTIVITY,
                PMA.IDACTIVITY) || ' - ' || COALESCE(PMAR.NMACTIVITY,
                PMA.NMACTIVITY) 
            FROM
                PMACTREVISION PMAR 
            INNER JOIN
                PMACTIVITY PMA 
                    ON PMA.CDACTIVITY=PMAR.CDACTIVITY 
            WHERE
                PMAR.CDASSOC=RISKANA.CDASSOC) 
            WHEN RISKANA.FGRISKANAPARENT=9 THEN (SELECT
                COALESCE(PMS.IDACTIVITY,
                PMA.IDACTIVITY) || ' - ' || COALESCE(PMS.NMACTIVITY,
                PMA.NMACTIVITY) 
            FROM
                PMSTRUCT PMS 
            INNER JOIN
                PMACTIVITY PMA 
                    ON PMA.CDACTIVITY=PMS.CDACTIVITY 
            INNER JOIN
                PMACTTYPE PMAT 
                    ON PMAT.CDACTTYPE=PMA.CDACTTYPE 
                    AND PMAT.FGTYPE IN (2,
                3) 
            WHERE
                PMS.CDASSOC=RISKANA.CDASSOC) 
            WHEN RISKANA.FGRISKANAPARENT IN (10,
            11) THEN (SELECT
                NMIDTASK || ' - ' || NMTASK 
            FROM
                PRTASK 
            WHERE
                CDBASETASK=CDTASK 
                AND CDASSOC=RISKANA.CDASSOC) 
            WHEN RISKANA.FGRISKANAPARENT=12 THEN (SELECT
                NMIDTASK || ' - ' || NMTASK 
            FROM
                PRTASK 
            WHERE
                CDBASETASK <> CDTASK 
                AND CDASSOC=RISKANA.CDASSOC) 
            WHEN RISKANA.FGRISKANAPARENT=13 THEN (SELECT
                IDOBJECT || ' - ' || NMOBJECT 
            FROM
                OBOBJECT 
            WHERE
                CDASSOC=RISKANA.CDASSOC) 
            ELSE NULL 
        END) AS NMRISKPARENT,
        (SELECT
            CAST(GNATTRIB.DSVALUE AS TEXT) 
        FROM
            GNASSOCATTRIB GNATTRIB 
        INNER JOIN
            ADATTRIBUTE ADAT 
                ON ADAT.CDATTRIBUTE=GNATTRIB.CDATTRIBUTE 
        WHERE
            GNATTRIB.CDATTRIBUTE=2 
            AND GNATTRIB.CDASSOC=RIRISKANA.CDASSOC) AS DSATTRIBUTE22097922,
        (SELECT
            CAST(GNATTRIB.DSVALUE AS TEXT) 
        FROM
            GNASSOCATTRIB GNATTRIB 
        INNER JOIN
            ADATTRIBUTE ADAT 
                ON ADAT.CDATTRIBUTE=GNATTRIB.CDATTRIBUTE 
        WHERE
            GNATTRIB.CDATTRIBUTE=3 
            AND GNATTRIB.CDASSOC=RIRISKANA.CDASSOC) AS DSATTRIBUTE32097922,
        (SELECT
            CAST(GNATTRIB.DSVALUE AS TEXT) 
        FROM
            GNASSOCATTRIB GNATTRIB 
        INNER JOIN
            ADATTRIBUTE ADAT 
                ON ADAT.CDATTRIBUTE=GNATTRIB.CDATTRIBUTE 
        WHERE
            GNATTRIB.CDATTRIBUTE=1 
            AND GNATTRIB.CDASSOC=RIRISKANA.CDASSOC) AS DSATTRIBUTE12097922,
        (SELECT
            CAST(GNATTRIB.DSVALUE AS TEXT) 
        FROM
            GNASSOCATTRIB GNATTRIB 
        INNER JOIN
            ADATTRIBUTE ADAT 
                ON ADAT.CDATTRIBUTE=GNATTRIB.CDATTRIBUTE 
        WHERE
            GNATTRIB.CDATTRIBUTE=4 
            AND GNATTRIB.CDASSOC=RIRISKANA.CDASSOC) AS DSATTRIBUTE42097922 
    FROM
        GNASSOCRISKANA RISKANA 
    INNER JOIN
        RIRISKANALYSIS RIRISKANA 
            ON RIRISKANA.CDRISKANALYSIS=RISKANA.CDRISKANALYSIS 
    INNER JOIN
        RIRISK RIR 
            ON RIR.CDRISK=RIRISKANA.CDRISK 
    INNER JOIN
        RIRISKTYPE RRT 
            ON RRT.CDRISKTYPE=RIR.CDRISKTYPE 
    INNER JOIN
        GNGENTYPE GNGT 
            ON GNGT.CDGENTYPE=RIR.CDRISKTYPE 
    INNER JOIN
        GNASSOC GNA 
            ON GNA.CDASSOC=RIRISKANA.CDASSOC 
    INNER JOIN
        RIPLAN RP 
            ON RP.CDPLAN=RISKANA.CDPLAN 
            AND RP.CDREVISION=RISKANA.CDREVISION 
            AND RP.FGTEMPLATE=2 
    INNER JOIN
        GNREVISION GNR 
            ON GNR.CDREVISION=RP.CDREVISION 
    INNER JOIN
        GNGENTYPE GGTP 
            ON GGTP.CDGENTYPE=RP.CDGENTYPE 
            AND GGTP.FGACTIVE=1 
            AND GGTP.CDISOSYSTEM=215 
    INNER JOIN
        GNEVAL GNE 
            ON GNE.CDEVAL=RIRISKANA.CDEVAL 
    INNER JOIN
        GNREVCONFIG GNRC 
            ON (
                GNRC.CDREVCONFIG=GGTP.CDREVCONFIG
            ) 
    LEFT OUTER JOIN
        ADUSER ADU 
            ON ADU.CDUSER=RIRISKANA.CDRISKRESP 
    LEFT OUTER JOIN
        ADTEAM ADT 
            ON ADT.CDTEAM=RIRISKANA.CDRISKTEAM 
    LEFT OUTER JOIN
        ADDEPARTMENT ADC 
            ON ADC.CDDEPARTMENT=RP.CDBUSINESSUNIT 
    LEFT OUTER JOIN
        ADMEASUNITY ADM 
            ON ADM.CDMEASUNITY=RIRISKANA.CDMEASUNITY 
    LEFT OUTER JOIN
        RIRISKANAEVAL RIRISKANAE 
            ON RIRISKANAE.CDRISKANALYSIS=RIRISKANA.CDRISKANALYSIS 
            AND RIRISKANAE.FGCURRENT=1 
    LEFT OUTER JOIN
        RISTRUCTCALC RISCALC 
            ON RISCALC.CDPLAN=RP.CDPLAN 
            AND RISCALC.CDREVISION=RP.CDREVISION 
            AND RISCALC.CDASSOC=RIRISKANA.CDASSOC 
    LEFT OUTER JOIN
        GNEVALRESULTUSED GERU_IN 
            ON GERU_IN.CDEVALRESULTUSED=RIRISKANAE.CDEVALRESULTREAL 
    LEFT OUTER JOIN
        GNEVALRESULTUSED GERU_POT 
            ON GERU_POT.CDEVALRESULTUSED=RIRISKANAE.CDEVALRESULTPOT 
    LEFT OUTER JOIN
        GNEVALRESULTUSED GERU_RES 
            ON GERU_RES.CDEVALRESULTUSED=RIRISKANAE.CDEVALRESULTRESID 
    LEFT OUTER JOIN
        GNEVALRESULTUSED GERU_CTRLREAL 
            ON GERU_CTRLREAL.CDEVALRESULTUSED=RISCALC.CDEVALCTRLREAL 
    LEFT OUTER JOIN
        GNEVALRESULT GER_IN 
            ON GERU_IN.CDEVALRESULT=GER_IN.CDEVALRESULT 
    LEFT OUTER JOIN
        GNEVALRESULT GER_POT 
            ON GERU_POT.CDEVALRESULT=GER_POT.CDEVALRESULT 
    LEFT OUTER JOIN
        GNEVALRESULT GER_RESID 
            ON GERU_RES.CDEVALRESULT=GER_RESID.CDEVALRESULT 
    LEFT OUTER JOIN
        GNEVALRESULT GER_CTRLREAL 
            ON GER_CTRLREAL.CDEVALRESULT=GERU_CTRLREAL.CDEVALRESULT 
    LEFT OUTER JOIN
        GNASSOCRIPLAN GNARP 
            ON GNARP.CDPLAN=RP.CDPLAN 
            AND GNARP.CDREVISION=RP.CDREVISION 
    LEFT OUTER JOIN
        PMACTREVISION PMAR 
            ON PMAR.CDASSOC=GNARP.CDASSOC 
    LEFT OUTER JOIN
        PMACTIVITY PMAPROC 
            ON PMAPROC.CDACTIVITY=PMAR.CDACTIVITY 
    WHERE
        1=1 
        AND (
            RP.FGCURRENT=1 
            AND GNR.FGSTATUS=6
        ) 
        AND RP.FGSTATUS <> 3 
        AND (
            RP.FGCURRENT=1 
            AND GNR.FGSTATUS=6
        ) 
        AND RP.FGSTATUS <> 3 
        /**AND GNGT.CDGENTYPE=27 **/
        AND (
            RP.CDTYPEROLE IS NULL 
            OR EXISTS (
                SELECT
                    NULL 
                FROM
                    (SELECT
                        CHKUSRPERMTYPEROLE.CDTYPEROLE AS CDTYPEROLE,
                        CHKUSRPERMTYPEROLE.CDUSER 
                    FROM
                        (SELECT
                            PM.FGPERMISSIONTYPE,
                            PM.CDUSER,
                            PM.CDTYPEROLE 
                        FROM
                            GNUSERPERMTYPEROLE PM 
                        WHERE
                            1=1 
                            AND PM.CDUSER <> -1 
                            AND PM.CDPERMISSION=6 /* Nao retirar este comentario */
                        UNION
                        ALL SELECT
                            PM.FGPERMISSIONTYPE,
                            US.CDUSER AS CDUSER,
                            PM.CDTYPEROLE 
                        FROM
                            GNUSERPERMTYPEROLE PM CROSS 
                        JOIN
                            ADUSER US 
                        WHERE
                            1=1 
                            AND PM.CDUSER=-1 
                            AND US.FGUSERENABLED=1 
                            AND PM.CDPERMISSION=6
                    ) CHKUSRPERMTYPEROLE 
                GROUP BY
                    CHKUSRPERMTYPEROLE.CDTYPEROLE,
                    CHKUSRPERMTYPEROLE.CDUSER 
                HAVING
                    MAX(CHKUSRPERMTYPEROLE.FGPERMISSIONTYPE)=1) CHKPERMTYPEROLE 
            WHERE
                CHKPERMTYPEROLE.CDTYPEROLE=RP.CDTYPEROLE 
                AND (
                    CHKPERMTYPEROLE.CDUSER=1 
                    OR 1=-1
                )
            ))) RIESGOS
LEFT JOIN
(SELECT
        CTRLANA.CDASSOCCONTROLANA,
        CTRLANA.CDASSOCCONTROLANA AS CDASSOCANA,
        CTRLANA.CDASSOC,
        CTRLANA.CDCTRLANABASELINK,
        CTRLANA.FGCTRLANAPARENT,
        CTRLANA.FGCONTROLASSOCTYPE,
        RICONTROLANA.CDCONTROLANALYSIS,
        RICONTROLANA.IDCONTROLANALYSIS || ' - ' || RIC.NMCONTROL AS CONTROL,
        RICONTROLANA.IDCONTROLANALYSIS,
        RICONTROLANA.CDASSOC AS CDASSOCANALYSIS,
        RICONTROLANA.DTNEXTEVAL,
        RICONTROLANA.VLCOST,
        RICONTROLANA.FGRELEVANT,
        RICONTROLANA.FGIMPLEMENT,
        RICONTROLANA.DTIMPLEMENT,
        RICONTROLANA.CDCONTROLRESP,
        RICONTROLANA.CDCONTROLTEAM,
        RICONTROLANA.FGAUTOMATIONTYPE,
        RICONTROLANA.FGCONTROLCHARACT,
        RICONTROLANA.FGCONTROLFREQ,
        RICONTROLANA.CDTOOLSANALISYS,
        RICONTROLANA.CDMEASUNITY,
        RICONTROLANA.DSCONTROLANALYSIS,
        RICONTROLANA.CDEVAL,
        RICONTROLANA.CDEVALREVISION,
        RICONTROLANA.CDEVALRESULTDESIGN,
        RICONTROLANA.CDEVALRESULTTEST,
        RP.CDPLAN,
        RP.CDREVISION,
        RP.IDPLAN,
        RP.NMPLAN,
        RP.IDPLAN || ' - ' || RP.NMPLAN AS PLANN,
        RP.CDBUSINESSUNIT,
        RP.CDISOSYSTEM,
        RP.CDASSOC AS CDASSOCPLAN,
        RP.FGDEFAULT,
        RP.FGTEMPLATE,
        RP.CDTEMPLATEREV,
        RIC.CDASSOC AS CDASSOCCONTROL,
        RIC.FGENABLED,
        RIC.CDCONTROL,
        RIC.IDCONTROL AS ID,
        RIC.NMCONTROL,
        RIC.CDCONTROLTYPE,
        RIC.FGSYMBOL,
        RIC.DSCONTROL,
        GNGT.CDGENTYPE,
        GNGT.NMGENTYPE AS NMTYPE,
        GNGT.IDGENTYPE || ' - ' || GNGT.NMGENTYPE AS TYPE,
        GNR.FGSTATUS AS FGREVISION,
        GNR.IDREVISION,
        GGTP.CDISOSYSTEM AS CDPROD,
        ADC.IDDEPARTMENT || ' - ' || ADC.NMDEPARTMENT AS NMBUSINESSUNIT,
        ADU.IDUSER,
        ADU.NMUSER,
        ADT.IDTEAM,
        ADT.NMTEAM,
        (CASE 
            WHEN RICONTROLANA.CDMEASUNITY IS NOT NULL THEN ADM.IDMEASUNITY || ' - ' || ADM.NMMEASUNITY 
            ELSE NULL 
        END) AS MEASUNITY,
        (CASE 
            WHEN CTRLANA.FGCTRLANAPARENT IN (3,
            4) THEN (SELECT
                RIR.DSRISK 
            FROM
                RIRISKANALYSIS RRA 
            INNER JOIN
                RIRISK RIR 
                    ON RRA.CDRISK=RIR.CDRISK 
            WHERE
                RRA.CDASSOC=CTRLANA.CDASSOC) 
            ELSE NULL 
        END) AS DSRISK,
        LASTTEST.CDTESTEXEC AS CDLASTEXEC,
        LASTTEST.VLRESULT AS VLRESULT_TESTPLAN,
        LASTTEST.FGRESULT AS FGTESTRESULT,
        LASTTEST.DTTEST AS DTEXEC_TESTPLAN,
        COALESCE(LASTTEST.NRSAMPLESIZE,
        0) AS QTY_SAMPLES,
        LASTTEST.NRSAMPLESIZE AS NR_SAMPLES,
        LASTTEST.NRSAMPLEFAIL AS NR_SAMPLEFAIL,
        LASTTEST.NRSAMPLEPASS AS NR_SAMPLEPASS,
        LASTTEST.FGCUSTOMRESULT,
        LASTTEST.CDUSEREXECTEST AS TESTPLANEXEC_CDUSER,
        TESTPLANEXEC_ADUSER.IDUSER || ' - ' || TESTPLANEXEC_ADUSER.NMUSER AS TESTPLANEXEC_USER,
        TESTPLANEXEC_ADUSER.IDUSER AS TESTPLANEXEC_IDUSER,
        TESTPLANEXEC_ADUSER.NMUSER AS TESTPLANEXEC_NMUSER,
        GNTESTEXECEVAL.FGRESULT,
        GNTESTEXECEVAL.CDTESTEVAL,
        GNTESTEXECEVAL.NMTESTEVAL,
        GNTESTEXECEVAL.FGSYMBOL AS FGRESULTSYMBOL,
        GNTESTEXECEVAL.IDCOLOR,
        GERDESIGN.NMEVALRESULT AS NMEVALRESULT_DESIGN,
        GERDESIGN.IDCOLOR AS IDCOLOR_DESIGN,
        GERTEST.NMEVALRESULT AS NMEVALRESULT_TEST,
        GERTEST.IDCOLOR AS IDCOLOR_TEST,
        CTRLEVALAPPROV.CDCONTROLANAEVAL AS CDEVALINAPPROV,
        RICONTROLANAE.CDCONTROLANAEVAL,
        RICONTROLANAE.IDCONTROLANAEVAL,
        RICONTROLANAE.DTCONTROLANAEVAL,
        RICONTROLANAE.CDASSOC AS CDASSOCCONTROLANAEVAL,
        RICONTROLANAE.FGCURRENT,
        RICONTROLANAE.CDRESULTEVAL AS CDEVALRESULTREAL,
        GERU.VLEVALRESULT AS VLEVALRESULTREAL,
        GER.NMEVALRESULT AS NMEVALRESULT_REAL,
        GER.IDCOLOR AS IDCOLOR_REAL,
        ('{"fground":"1","qtdecimal":"1"}') AS FGROUND_QTDECIMAL_JSON,
        (SELECT
            MIN(NRORDER) 
        FROM
            RIPLANITEMORDER 
        WHERE
            CDPLAN=CTRLANA.CDPLAN 
            AND CDREVISION=CTRLANA.CDREVISION 
            AND CDCONTROLANALYSIS=CTRLANA.CDASSOCCONTROLANA) AS NRORDER,
        (CASE 
            WHEN (SELECT
                CDASSOC 
            FROM
                GNASSOCRIPLAN 
            WHERE
                CDPLAN=RP.CDPLAN 
                AND CDREVISION=RP.CDREVISION) IS NOT NULL THEN (SELECT
                CDASSOC 
            FROM
                GNASSOCRIPLAN 
            WHERE
                CDPLAN=RP.CDPLAN 
                AND CDREVISION=RP.CDREVISION) 
            ELSE (SELECT
                CDASSOC 
            FROM
                RIPLAN 
            WHERE
                CDPLAN=RP.CDPLAN 
                AND CDREVISION=RP.CDREVISION) 
        END) AS CDASSOC_PLAN,
        (CASE 
            WHEN EXISTS (SELECT
                1 
            FROM
                RIRISKANALYSIS 
            WHERE
                CDASSOC=CTRLANA.CDASSOC) THEN 1 
            ELSE 0 
        END) AS HAS_RISKFATHER,
        GNE.IDEVAL || ' - ' || GNE.NMEVAL AS NMEVAL,
        GNE.FGTYPE AS FGEVALTYPE,
        0 AS HAS_CHILD,
        (SELECT
            COUNT(1) 
        FROM
            GNASSOCWORKFLOW GNAW 
        INNER JOIN
            WFPROCESS WFP 
                ON GNAW.IDPROCESS=WFP.IDOBJECT 
        WHERE
            WFP.FGSTATUS <= 5 
            AND WFP.CDPRODAUTOMATION=160 
            AND GNAW.CDASSOC=RICONTROLANA.CDASSOC) AS ASSOC_INCIDENT,
        (SELECT
            COUNT(1) 
        FROM
            GNASSOCWORKFLOW GNAW 
        INNER JOIN
            WFPROCESS WFP 
                ON GNAW.IDPROCESS=WFP.IDOBJECT 
        WHERE
            WFP.FGSTATUS <= 5 
            AND WFP.CDPRODAUTOMATION=202 
            AND GNAW.CDASSOC=RICONTROLANA.CDASSOC) AS ASSOC_PROBLEM,
        (SELECT
            COUNT(1) 
        FROM
            GNASSOCWORKFLOW GNAW 
        INNER JOIN
            WFPROCESS WFP 
                ON GNAW.IDPROCESS=WFP.IDOBJECT 
        WHERE
            WFP.FGSTATUS <= 5 
            AND GNAW.CDASSOC=RICONTROLANA.CDASSOC 
            AND WFP.CDPRODAUTOMATION NOT IN(
                160,202
            )) AS ASSOC_WORKFLOW,
        (SELECT
            COUNT(1) 
        FROM
            GNASSOCACTIONPLAN 
        WHERE
            CDASSOC=RICONTROLANA.CDASSOC) AS ASSOC_ACTIONPLAN,
        (SELECT
            COUNT(1) 
        FROM
            GNASSOCACTIONPLAN 
        WHERE
            CDASSOC=RICONTROLANAE.CDASSOC) AS ASSOC_ACTIONPLAN_EVAL,
        (SELECT
            COUNT(1) 
        FROM
            RICONTROLANABESTPR 
        WHERE
            CDCONTROLANALYSIS=RICONTROLANA.CDCONTROLANALYSIS) AS ASSOC_BESTPRACTICE,
        (SELECT
            COUNT(1) 
        FROM
            RICONTROLANAOBJECT 
        WHERE
            CDCONTROLANALYSIS=RICONTROLANA.CDCONTROLANALYSIS) AS ASSOC_OBJECTIVE,
        (( SELECT
            COUNT(1) 
        FROM
            GNSTRUCT GNS 
        INNER JOIN
            RISTRUCTCAUSE RSC 
                ON RSC.CDSTRUCT=GNS.CDSTRUCT 
        INNER JOIN
            OBCAUSE OBC 
                ON OBC.CDCAUSE=RSC.CDCAUSE 
        WHERE
            GNS.CDTOOLANALYSIS=RICONTROLANA.CDTOOLSANALISYS) + (SELECT
            COUNT(1) 
        FROM
            GNSTRUCT GNS 
        INNER JOIN
            GNANALISYS GNA 
                ON GNA.CDANALISYS=GNS.CDANALISYS 
        INNER JOIN
            GNANALISYS GNANEXT 
                ON GNANEXT.CDANALISYSEXT=GNA.CDANALISYS 
        WHERE
            GNANEXT.CDTOOLSANALISYS=RICONTROLANA.CDTOOLSANALISYS)) AS ASSOC_CAUSE,
        (SELECT
            COUNT(1) 
        FROM
            GNASSOCMETRIC 
        WHERE
            CDASSOC=RICONTROLANA.CDASSOC) AS ASSOC_METRIC,
        (SELECT
            COUNT(1) 
        FROM
            GNASSOCPROJECT 
        WHERE
            CDASSOC=RICONTROLANA.CDASSOC) AS ASSOC_PROJECT,
        (SELECT
            COUNT(1) 
        FROM
            GNASSOCSURVEY GNAS 
        INNER JOIN
            SVSURVEY SVS 
                ON SVS.CDSURVEY=GNAS.CDSURVEY 
        WHERE
            GNAS.CDASSOC=RICONTROLANA.CDASSOC) AS ASSOC_SURVEY,
        (SELECT
            COUNT(1) 
        FROM
            GNASSOCATTACH 
        WHERE
            CDASSOC=RICONTROLANA.CDASSOC) AS ASSOC_ATTACHMENT,
        (SELECT
            COUNT(1) 
        FROM
            GNASSOCDOCUMENT 
        WHERE
            CDASSOC=RICONTROLANA.CDASSOC) AS ASSOC_DOCUMENT,
        (SELECT
            COUNT(1) 
        FROM
            RICONTROLANACOMMEN 
        WHERE
            CDCONTROLANALYSIS=RICONTROLANA.CDCONTROLANALYSIS) AS ASSOC_COMMENT,
        (( SELECT
            COUNT(1) 
        FROM
            AUAUDIT 
        INNER JOIN
            RICONTROLANAAUDIT 
                ON RICONTROLANAAUDIT.CDASSOC=AUAUDIT.CDASSOC 
                AND RICONTROLANAAUDIT.CDASSOCCONTROLANA=CTRLANA.CDASSOCCONTROLANA 
        WHERE
            AUAUDIT.FGMODEL IN (
                2, 4
            )) + (SELECT
            COUNT(1) 
        FROM
            AUAUDIT 
        INNER JOIN
            AUSCOPESTRUCT 
                ON AUSCOPESTRUCT.CDSCOPEDEFINITION=AUAUDIT.CDSCOPEDEFINITION 
                AND AUSCOPESTRUCT.CDASSOCCONTROLANA=CTRLANA.CDASSOCCONTROLANA 
        WHERE
            AUAUDIT.FGMODEL IN (
                2, 4
            ))) AS ASSOC_AUDIT,
        (SELECT
            COUNT(1) 
        FROM
            GNASSOCTESTPLAN GNATP 
        INNER JOIN
            GNTESTPLAN GNTP 
                ON GNATP.CDTESTPLAN=GNTP.CDTESTPLAN 
        INNER JOIN
            GNTESTEXEC GNTX 
                ON GNTP.CDTESTPLAN=GNTX.CDTESTPLAN 
        WHERE
            GNATP.CDASSOC=RICONTROLANA.CDASSOC) AS QTY_TEST,
        (CASE 
            WHEN RICONTROLANA.FGRELEVANT=1 THEN '#{100092}' 
            ELSE '#{100093}' 
        END) AS NMRELEVANT,
        (CASE 
            WHEN RICONTROLANA.FGIMPLEMENT=1 THEN '#{201482}' 
            WHEN RICONTROLANA.FGIMPLEMENT=2 THEN '#{214694}' 
            WHEN RICONTROLANA.FGIMPLEMENT=3 THEN '#{214695}' 
            ELSE NULL 
        END) AS NMIMPLEMENT,
        (CASE 
            WHEN RICONTROLANA.FGAUTOMATIONTYPE=1 THEN '#{201018}' 
            WHEN RICONTROLANA.FGAUTOMATIONTYPE=2 THEN '#{213186}' 
            WHEN RICONTROLANA.FGAUTOMATIONTYPE=3 THEN '#{201017}' 
            ELSE NULL 
        END) AS NMAUTOMATIONTYPE,
        (CASE 
            WHEN RICONTROLANA.FGCONTROLCHARACT=1 THEN '#{201481}' 
            WHEN RICONTROLANA.FGCONTROLCHARACT=2 THEN '#{201485}' 
            WHEN RICONTROLANA.FGCONTROLCHARACT=3 THEN '#{220245}' 
            ELSE NULL 
        END) AS NMCONTROLCHARACT,
        (CASE 
            WHEN RICONTROLANA.FGCONTROLFREQ=1 THEN '#{201488}' 
            WHEN RICONTROLANA.FGCONTROLFREQ=2 THEN '#{110601}' 
            WHEN RICONTROLANA.FGCONTROLFREQ=3 THEN '#{107701}' 
            WHEN RICONTROLANA.FGCONTROLFREQ=4 THEN '#{102557}' 
            WHEN RICONTROLANA.FGCONTROLFREQ=5 THEN '#{102563}' 
            WHEN RICONTROLANA.FGCONTROLFREQ=6 THEN '#{102561}' 
            WHEN RICONTROLANA.FGCONTROLFREQ=7 THEN '#{102548}' 
            WHEN RICONTROLANA.FGCONTROLFREQ=8 THEN '#{108481}' 
            ELSE NULL 
        END) AS NMCONTROLFREQ,
        RRA.IDRISKANALYSIS,
        RR.NMRISK,
        RICONTROLANA.CDCONTROLANABASE,
        CAST(RRA.DSRISKANALYSIS AS VARCHAR(4000)) AS DSRISKANALYSIS,
        GNERU_REAL.VLEVALRESULT AS VLEVALRISKREAL,
        GNERU_POT.VLEVALRESULT AS VLEVALRISKPOT,
        GNERU_RESID.VLEVALRESULT AS VLEVALRISKRESID,
        GNER_REAL.NMEVALRESULT AS NMEVALRESULTREAL,
        GNER_POT.NMEVALRESULT AS NMEVALRESULTPOT,
        GNER_RESID.NMEVALRESULT AS NMEVALRESULTRESID,
        PMAPROC.IDACTIVITY AS IDPROCESS,
        PMAPROC.NMACTIVITY AS NMPROCESS,
        (CASE 
            WHEN LASTTEST.VLRESULT >= '100' THEN '#{301300}' 
            WHEN LASTTEST.VLRESULT < '100' THEN '#{219776}' 
            ELSE '' 
        END) AS TESTRESULT,
        GNTESTPLAN.DTNEXTEXECUTION AS TESTNEXTEXEC 
    FROM
        GNASSOCCONTROLANA CTRLANA 
    INNER JOIN
        RICONTROLANALYSIS RICONTROLANA 
            ON RICONTROLANA.CDCONTROLANALYSIS=CTRLANA.CDCONTROLANALYSIS 
    INNER JOIN
        RICONTROL RIC 
            ON RIC.CDCONTROL=RICONTROLANA.CDCONTROL 
    INNER JOIN
        RICONTROLTYPE RCT 
            ON RCT.CDCONTROLTYPE=RIC.CDCONTROLTYPE 
    INNER JOIN
        GNGENTYPE GNGT 
            ON GNGT.CDGENTYPE=RIC.CDCONTROLTYPE 
    INNER JOIN
        GNASSOC GNA 
            ON GNA.CDASSOC=RICONTROLANA.CDASSOC 
    INNER JOIN
        RIPLAN RP 
            ON RP.CDPLAN=CTRLANA.CDPLAN 
            AND RP.CDREVISION=CTRLANA.CDREVISION 
            AND RP.FGTEMPLATE=2 
    INNER JOIN
        GNREVISION GNR 
            ON GNR.CDREVISION=RP.CDREVISION 
    INNER JOIN
        GNGENTYPE GGTP 
            ON GGTP.CDGENTYPE=RP.CDGENTYPE 
            AND GGTP.FGACTIVE=1 
            AND GGTP.CDISOSYSTEM=215 
    INNER JOIN
        RIPLANTYPE RIPT 
            ON RIPT.CDPLANTYPE=GGTP.CDGENTYPE 
    INNER JOIN
        GNREVCONFIG GNRC 
            ON (
                GNRC.CDREVCONFIG=GGTP.CDREVCONFIG
            ) 
    LEFT OUTER JOIN
        GNASSOCTESTPLAN GNATP 
            ON RICONTROLANA.CDASSOC=GNATP.CDASSOC 
    LEFT OUTER JOIN
        GNTESTPLAN GNTP 
            ON GNATP.CDTESTPLAN=GNTP.CDTESTPLAN 
    LEFT OUTER JOIN
        GNTESTEXEC LASTTEST 
            ON LASTTEST.CDTESTPLAN=GNTP.CDTESTPLAN 
            AND LASTTEST.CDTESTEXEC=RICONTROLANA.CDLASTEXEC 
    LEFT OUTER JOIN
        GNTESTEXECEVAL 
            ON LASTTEST.CDTESTEXEC=GNTESTEXECEVAL.CDTESTEXEC 
            AND GNTESTEXECEVAL.FGRESULTTEST=1 
    LEFT OUTER JOIN
        ADUSER ADU 
            ON ADU.CDUSER=RICONTROLANA.CDCONTROLRESP 
    LEFT OUTER JOIN
        ADTEAM ADT 
            ON ADT.CDTEAM=RICONTROLANA.CDCONTROLTEAM 
    LEFT OUTER JOIN
        ADDEPARTMENT ADC 
            ON ADC.CDDEPARTMENT=RP.CDBUSINESSUNIT 
    LEFT OUTER JOIN
        ADMEASUNITY ADM 
            ON ADM.CDMEASUNITY=RICONTROLANA.CDMEASUNITY 
    LEFT OUTER JOIN
        RICONTROLANAEVAL CTRLEVALAPPROV 
            ON CTRLEVALAPPROV.CDCONTROLANALYSIS=RICONTROLANA.CDCONTROLANALYSIS 
            AND CTRLEVALAPPROV.FGCURRENT=3 
    LEFT OUTER JOIN
        RICONTROLANAEVAL RICONTROLANAE 
            ON RICONTROLANAE.CDCONTROLANALYSIS=RICONTROLANA.CDCONTROLANALYSIS 
            AND RICONTROLANAE.FGCURRENT=1 
    LEFT OUTER JOIN
        ADUSER TESTPLANEXEC_ADUSER 
            ON TESTPLANEXEC_ADUSER.CDUSER=LASTTEST.CDUSEREXECTEST 
    LEFT OUTER JOIN
        GNEVALRESULTUSED GERU 
            ON GERU.CDEVALRESULTUSED=RICONTROLANAE.CDRESULTEVAL 
    LEFT OUTER JOIN
        GNEVALRESULT GER 
            ON GERU.CDEVALRESULT=GER.CDEVALRESULT 
    LEFT OUTER JOIN
        GNEVAL GNE 
            ON GNE.CDEVAL=RICONTROLANA.CDEVAL 
    LEFT OUTER JOIN
        GNEVALRESULT GERDESIGN 
            ON GERDESIGN.CDEVALRESULT=RICONTROLANA.CDEVALRESULTDESIGN 
    LEFT OUTER JOIN
        GNEVALRESULT GERTEST 
            ON GERTEST.CDEVALRESULT=RICONTROLANA.CDEVALRESULTTEST 
    LEFT OUTER JOIN
        RIRISKANALYSIS RRA 
            ON RRA.CDASSOC=CTRLANA.CDASSOC 
    LEFT OUTER JOIN
        RIRISK RR 
            ON RR.CDRISK=RRA.CDRISK 
    LEFT OUTER JOIN
        RIRISKANAEVAL RRAE 
            ON RRAE.CDRISKANALYSIS=RRA.CDRISKANALYSIS 
            AND RRAE.FGCURRENT=1 
    LEFT OUTER JOIN
        GNEVALRESULTUSED GNERU_REAL 
            ON GNERU_REAL.CDEVALRESULTUSED=RRAE.CDEVALRESULTREAL 
    LEFT OUTER JOIN
        GNEVALRESULTUSED GNERU_POT 
            ON GNERU_POT.CDEVALRESULTUSED=RRAE.CDEVALRESULTPOT 
    LEFT OUTER JOIN
        GNEVALRESULTUSED GNERU_RESID 
            ON GNERU_RESID.CDEVALRESULTUSED=RRAE.CDEVALRESULTRESID 
    LEFT OUTER JOIN
        GNEVALRESULT GNER_REAL 
            ON GNER_REAL.CDEVALRESULT=GNERU_REAL.CDEVALRESULT 
    LEFT OUTER JOIN
        GNEVALRESULT GNER_POT 
            ON GNER_POT.CDEVALRESULT=GNERU_POT.CDEVALRESULT 
    LEFT OUTER JOIN
        GNEVALRESULT GNER_RESID 
            ON GNER_RESID.CDEVALRESULT=GNERU_RESID.CDEVALRESULT 
    LEFT OUTER JOIN
        GNASSOCRIPLAN GNARP 
            ON GNARP.CDPLAN=RP.CDPLAN 
            AND GNARP.CDREVISION=RP.CDREVISION 
    LEFT OUTER JOIN
        GNASSOCTESTPLAN 
            ON GNASSOCTESTPLAN.CDASSOC=RICONTROLANA.CDASSOC 
    LEFT OUTER JOIN
        GNTESTPLAN 
            ON GNTESTPLAN.CDTESTPLAN=GNASSOCTESTPLAN.CDTESTPLAN 
    LEFT OUTER JOIN
        PMACTREVISION PMAR 
            ON PMAR.CDASSOC=GNARP.CDASSOC 
    LEFT OUTER JOIN
        PMACTIVITY PMAPROC 
            ON PMAPROC.CDACTIVITY=PMAR.CDACTIVITY 
    WHERE
        1=1 
        AND (
            RP.CDTYPEROLE IS NULL 
            OR EXISTS (
                SELECT
                    NULL 
                FROM
                    (SELECT
                        CHKUSRPERMTYPEROLE.CDTYPEROLE AS CDTYPEROLE,
                        CHKUSRPERMTYPEROLE.CDUSER 
                    FROM
                        (SELECT
                            PM.FGPERMISSIONTYPE,
                            PM.CDUSER,
                            PM.CDTYPEROLE 
                        FROM
                            GNUSERPERMTYPEROLE PM 
                        WHERE
                            1=1 
                            AND PM.CDUSER <> -1 
                            AND PM.CDPERMISSION=6 /* Nao retirar este comentario */
                        UNION
                        ALL SELECT
                            PM.FGPERMISSIONTYPE,
                            US.CDUSER AS CDUSER,
                            PM.CDTYPEROLE 
                        FROM
                            GNUSERPERMTYPEROLE PM CROSS 
                        JOIN
                            ADUSER US 
                        WHERE
                            1=1 
                            AND PM.CDUSER=-1 
                            AND US.FGUSERENABLED=1 
                            AND PM.CDPERMISSION=6
                    ) CHKUSRPERMTYPEROLE 
                GROUP BY
                    CHKUSRPERMTYPEROLE.CDTYPEROLE,
                    CHKUSRPERMTYPEROLE.CDUSER 
                HAVING
                    MAX(CHKUSRPERMTYPEROLE.FGPERMISSIONTYPE)=1) CHKPERMTYPEROLE 
            WHERE
                CHKPERMTYPEROLE.CDTYPEROLE=RP.CDTYPEROLE 
                AND (
                    CHKPERMTYPEROLE.CDUSER=1 
                    OR 1=-1
                )
            )) 
        AND (RP.FGCURRENT=1 
        AND GNR.FGSTATUS=6) 
        AND RP.FGSTATUS <> 3 
        AND (RP.FGCURRENT=1 
        AND GNR.FGSTATUS=6) 
        AND RP.FGSTATUS <> 3 
        AND (RP.CDTYPEROLE IS NULL 
        OR EXISTS (SELECT
            NULL 
        FROM
            (SELECT
                CHKUSRPERMTYPEROLE.CDTYPEROLE AS CDTYPEROLE,
                CHKUSRPERMTYPEROLE.CDUSER 
            FROM
                (SELECT
                    PM.FGPERMISSIONTYPE,
                    PM.CDUSER,
                    PM.CDTYPEROLE 
                FROM
                    GNUSERPERMTYPEROLE PM 
                WHERE
                    1=1 
                    AND PM.CDUSER <> -1 
                    AND PM.CDPERMISSION=6 /* Nao retirar este comentario */
                UNION
                ALL SELECT
                    PM.FGPERMISSIONTYPE,
                    US.CDUSER AS CDUSER,
                    PM.CDTYPEROLE 
                FROM
                    GNUSERPERMTYPEROLE PM CROSS 
                JOIN
                    ADUSER US 
                WHERE
                    1=1 
                    AND PM.CDUSER=-1 
                    AND US.FGUSERENABLED=1 
                    AND PM.CDPERMISSION=6
            ) CHKUSRPERMTYPEROLE 
        GROUP BY
            CHKUSRPERMTYPEROLE.CDTYPEROLE,
            CHKUSRPERMTYPEROLE.CDUSER 
        HAVING
            MAX(CHKUSRPERMTYPEROLE.FGPERMISSIONTYPE)=1) CHKPERMTYPEROLE 
    WHERE
        CHKPERMTYPEROLE.CDTYPEROLE=RP.CDTYPEROLE 
        AND (
            CHKPERMTYPEROLE.CDUSER=1 
            OR 1=-1
        )
    ))) CONTROLES ON RIESGOS.IDRISKANALYSIS = CONTROLES.IDRISKANALYSIS